import { Branch, Department, Shift, User, AttendanceRecord, LeaveRequest, AuditLog, BulkImportBatch } from '@/types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'b-1',
    code: 'HQ-JKT',
    name: 'Headquarter Sudirman',
    city: 'Jakarta Selatan',
    timezone: 'Asia/Jakarta',
    latitude: -6.2146,
    longitude: 106.8214,
    radiusMeters: 150,
  },
  {
    id: 'b-2',
    code: 'SUB-HUB',
    name: 'Surabaya Tech & Operations',
    city: 'Surabaya',
    timezone: 'Asia/Jakarta',
    latitude: -7.2575,
    longitude: 112.7521,
    radiusMeters: 200,
  },
  {
    id: 'b-3',
    code: 'BDG-RND',
    name: 'Bandung R&D Digital Center',
    city: 'Bandung',
    timezone: 'Asia/Jakarta',
    latitude: -6.9175,
    longitude: 107.6191,
    radiusMeters: 250,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'd-1', code: 'ENG', name: 'Software Engineering & IT', branchId: 'b-1' },
  { id: 'd-2', code: 'HRD', name: 'Human Resource & People Ops', branchId: 'b-1' },
  { id: 'd-3', code: 'FIN', name: 'Finance & Accounting', branchId: 'b-1' },
  { id: 'd-4', code: 'OPS', name: 'Operations & Logistics', branchId: 'b-2' },
  { id: 'd-5', code: 'PRD', name: 'Product & Design', branchId: 'b-3' },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 's-1',
    code: 'STD-0817',
    name: 'Standard Office (08:00 - 17:00)',
    startTime: '08:00',
    endTime: '17:00',
    gracePeriodMins: 15,
    breakMins: 60,
    isFlexible: false,
    workDays: 'MON,TUE,WED,THU,FRI',
  },
  {
    id: 's-2',
    code: 'MORN-0615',
    name: 'Morning Shift (06:00 - 15:00)',
    startTime: '06:00',
    endTime: '15:00',
    gracePeriodMins: 10,
    breakMins: 60,
    isFlexible: false,
    workDays: 'MON,TUE,WED,THU,FRI,SAT',
  },
  {
    id: 's-3',
    code: 'EVE-1423',
    name: 'Evening Shift (14:00 - 23:00)',
    startTime: '14:00',
    endTime: '23:00',
    gracePeriodMins: 10,
    breakMins: 60,
    isFlexible: false,
    workDays: 'MON,TUE,WED,THU,FRI,SAT',
  },
  {
    id: 's-4',
    code: 'FLEX-CORE',
    name: 'Flexible Core Hours (40h/week)',
    startTime: '09:00',
    endTime: '18:00',
    gracePeriodMins: 30,
    breakMins: 60,
    isFlexible: true,
    workDays: 'MON,TUE,WED,THU,FRI',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    employeeCode: 'EMP-0001',
    email: 'superadmin@enterprise.corp',
    fullName: 'Alexander Bramantyo',
    role: 'SUPER_ADMIN',
    jobTitle: 'VP of Technology & Systems',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+62 811-9988-100',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-4',
    shiftName: 'Flexible Core Hours (40h/week)',
  },
  {
    id: 'u-2',
    employeeCode: 'EMP-0002',
    email: 'hr.admin@enterprise.corp',
    fullName: 'Clarissa Maharani',
    role: 'HR_ADMIN',
    jobTitle: 'Lead People Operations & Payroll',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+62 812-4455-201',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-2',
    departmentName: 'Human Resource & People Ops',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-3',
    employeeCode: 'EMP-0003',
    email: 'manager.eng@enterprise.corp',
    fullName: 'Reza Pratama Kusuma',
    role: 'MANAGER',
    jobTitle: 'Engineering Manager',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+62 813-7788-302',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-4',
    employeeCode: 'EMP-0004',
    email: 'dimas.anggara@enterprise.corp',
    fullName: 'Dimas Anggara',
    role: 'EMPLOYEE',
    jobTitle: 'Senior Cloud Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+62 812-3344-403',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-5',
    employeeCode: 'EMP-0005',
    email: 'nadia.saphira@enterprise.corp',
    fullName: 'Nadia Saphira',
    role: 'EMPLOYEE',
    jobTitle: 'Frontend Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    phone: '+62 815-5566-504',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-6',
    employeeCode: 'EMP-0006',
    email: 'fajar.hidayat@enterprise.corp',
    fullName: 'Fajar Hidayat',
    role: 'EMPLOYEE',
    jobTitle: 'Fullstack Developer',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    phone: '+62 817-6677-605',
    isActive: true,
    branchId: 'b-2',
    branchName: 'Surabaya Tech & Operations',
    departmentId: 'd-4',
    departmentName: 'Operations & Logistics',
    shiftId: 's-2',
    shiftName: 'Morning Shift (06:00 - 15:00)',
  },
  {
    id: 'u-7',
    employeeCode: 'EMP-0007',
    email: 'sitialiyah@enterprise.corp',
    fullName: 'Siti Aliyah Putri',
    role: 'EMPLOYEE',
    jobTitle: 'Product Designer (UI/UX)',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+62 818-8899-706',
    isActive: true,
    branchId: 'b-3',
    branchName: 'Bandung R&D Digital Center',
    departmentId: 'd-5',
    departmentName: 'Product & Design',
    shiftId: 's-4',
    shiftName: 'Flexible Core Hours (40h/week)',
  },
  {
    id: 'u-8',
    employeeCode: 'EMP-0008',
    email: 'budi.santoso@enterprise.corp',
    fullName: 'Budi Santoso',
    role: 'EMPLOYEE',
    jobTitle: 'Financial Analyst',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    phone: '+62 819-1122-807',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-3',
    departmentName: 'Finance & Accounting',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [];
export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_IMPORT_BATCHES: BulkImportBatch[] = [];
