import { Branch, Department, Shift, User, AttendanceRecord, LeaveRequest, AuditLog, BulkImportBatch } from '@/types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'b-1',
    code: 'HQ-JKT',
    name: 'Headquarter Sudirman',
    city: 'Jakarta Selatan',
    timezone: 'Asia/Jakarta',
    latitude: -6.2146,
    longitude: 106.8214,
    radiusMeters: 150,
  },
  {
    id: 'b-2',
    code: 'SUB-HUB',
    name: 'Surabaya Tech & Operations',
    city: 'Surabaya',
    timezone: 'Asia/Jakarta',
    latitude: -7.2575,
    longitude: 112.7521,
    radiusMeters: 200,
  },
  {
    id: 'b-3',
    code: 'BDG-RND',
    name: 'Bandung R&D Digital Center',
    city: 'Bandung',
    timezone: 'Asia/Jakarta',
    latitude: -6.9175,
    longitude: 107.6191,
    radiusMeters: 250,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'd-1', code: 'ENG', name: 'Software Engineering & IT', branchId: 'b-1' },
  { id: 'd-2', code: 'HRD', name: 'Human Resource & People Ops', branchId: 'b-1' },
  { id: 'd-3', code: 'FIN', name: 'Finance & Accounting', branchId: 'b-1' },
  { id: 'd-4', code: 'OPS', name: 'Operations & Logistics', branchId: 'b-2' },
  { id: 'd-5', code: 'PRD', name: 'Product & Design', branchId: 'b-3' },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 's-1',
    code: 'STD-0817',
    name: 'Standard Office (08:00 - 17:00)',
    startTime: '08:00',
    endTime: '17:00',
    gracePeriodMins: 15,
    breakMins: 60,
    isFlexible: false,
    workDays: 'MON,TUE,WED,THU,FRI',
  },
  {
    id: 's-2',
    code: 'MORN-0615',
    name: 'Morning Shift (06:00 - 15:00)',
    startTime: '06:00',
    endTime: '15:00',
    gracePeriodMins: 10,
    breakMins: 60,
    isFlexible: false,
    workDays: 'MON,TUE,WED,THU,FRI,SAT',
  },
  {
    id: 's-3',
    code: 'EVE-1423',
    name: 'Evening Shift (14:00 - 23:00)',
    startTime: '14:00',
    endTime: '23:00',
    gracePeriodMins: 10,
    breakMins: 60,
    isFlexible: false,
    workDays: 'MON,TUE,WED,THU,FRI,SAT',
  },
  {
    id: 's-4',
    code: 'FLEX-CORE',
    name: 'Flexible Core Hours (40h/week)',
    startTime: '09:00',
    endTime: '18:00',
    gracePeriodMins: 30,
    breakMins: 60,
    isFlexible: true,
    workDays: 'MON,TUE,WED,THU,FRI',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    employeeCode: 'EMP-0001',
    email: 'superadmin@enterprise.corp',
    fullName: 'Alexander Bramantyo',
    role: 'SUPER_ADMIN',
    jobTitle: 'VP of Technology & Systems',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+62 811-9988-100',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-4',
    shiftName: 'Flexible Core Hours (40h/week)',
  },
  {
    id: 'u-2',
    employeeCode: 'EMP-0002',
    email: 'hr.admin@enterprise.corp',
    fullName: 'Clarissa Maharani',
    role: 'HR_ADMIN',
    jobTitle: 'Lead People Operations & Payroll',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+62 812-4455-201',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-2',
    departmentName: 'Human Resource & People Ops',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-3',
    employeeCode: 'EMP-0003',
    email: 'manager.eng@enterprise.corp',
    fullName: 'Reza Pratama Kusuma',
    role: 'MANAGER',
    jobTitle: 'Engineering Manager',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+62 813-7788-302',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-4',
    employeeCode: 'EMP-0004',
    email: 'dimas.anggara@enterprise.corp',
    fullName: 'Dimas Anggara',
    role: 'EMPLOYEE',
    jobTitle: 'Senior Cloud Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+62 812-3344-403',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-5',
    employeeCode: 'EMP-0005',
    email: 'nadia.saphira@enterprise.corp',
    fullName: 'Nadia Saphira',
    role: 'EMPLOYEE',
    jobTitle: 'Frontend Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    phone: '+62 815-5566-504',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-1',
    departmentName: 'Software Engineering & IT',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
  {
    id: 'u-6',
    employeeCode: 'EMP-0006',
    email: 'fajar.hidayat@enterprise.corp',
    fullName: 'Fajar Hidayat',
    role: 'EMPLOYEE',
    jobTitle: 'Fullstack Developer',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    phone: '+62 817-6677-605',
    isActive: true,
    branchId: 'b-2',
    branchName: 'Surabaya Tech & Operations',
    departmentId: 'd-4',
    departmentName: 'Operations & Logistics',
    shiftId: 's-2',
    shiftName: 'Morning Shift (06:00 - 15:00)',
  },
  {
    id: 'u-7',
    employeeCode: 'EMP-0007',
    email: 'sitialiyah@enterprise.corp',
    fullName: 'Siti Aliyah Putri',
    role: 'EMPLOYEE',
    jobTitle: 'Product Designer (UI/UX)',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+62 818-8899-706',
    isActive: true,
    branchId: 'b-3',
    branchName: 'Bandung R&D Digital Center',
    departmentId: 'd-5',
    departmentName: 'Product & Design',
    shiftId: 's-4',
    shiftName: 'Flexible Core Hours (40h/week)',
  },
  {
    id: 'u-8',
    employeeCode: 'EMP-0008',
    email: 'budi.santoso@enterprise.corp',
    fullName: 'Budi Santoso',
    role: 'EMPLOYEE',
    jobTitle: 'Financial Analyst',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    phone: '+62 819-1122-807',
    isActive: true,
    branchId: 'b-1',
    branchName: 'Headquarter Sudirman',
    departmentId: 'd-3',
    departmentName: 'Finance & Accounting',
    shiftId: 's-1',
    shiftName: 'Standard Office (08:00 - 17:00)',
  },
];

const todayStr = new Date().toISOString().split('T')[0];
const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    userId: 'u-4',
    employeeCode: 'EMP-0004',
    employeeName: 'Dimas Anggara',
    departmentName: 'Software Engineering & IT',
    branchName: 'Headquarter Sudirman',
    shiftName: 'Standard Office (08:00 - 17:00)',
    date: todayStr,
    checkIn: `${todayStr}T07:54:12.000Z`,
    checkOut: null,
    status: 'PRESENT',
    lateMinutes: 0,
    earlyMinutes: 0,
    overtimeMinutes: 0,
    effectiveWorkHours: 3.5,
    verificationMethod: 'WEB_KIOSK',
    ipAddress: '10.240.12.88',
    notes: 'Presensi Kios On-site via Facial Match',
    createdAt: `${todayStr}T07:54:12.000Z`,
  },
  {
    id: 'att-2',
    userId: 'u-5',
    employeeCode: 'EMP-0005',
    employeeName: 'Nadia Saphira',
    departmentName: 'Software Engineering & IT',
    branchName: 'Headquarter Sudirman',
    shiftName: 'Standard Office (08:00 - 17:00)',
    date: todayStr,
    checkIn: `${todayStr}T08:26:45.000Z`,
    checkOut: null,
    status: 'LATE',
    lateMinutes: 26,
    earlyMinutes: 0,
    overtimeMinutes: 0,
    effectiveWorkHours: 3.0,
    verificationMethod: 'MOBILE_GEO',
    ipAddress: '192.168.10.45',
    notes: 'Terlambat kendala MRT Lebak Bulus',
    createdAt: `${todayStr}T08:26:45.000Z`,
  },
  {
    id: 'att-3',
    userId: 'u-6',
    employeeCode: 'EMP-0006',
    employeeName: 'Fajar Hidayat',
    departmentName: 'Operations & Logistics',
    branchName: 'Surabaya Tech & Operations',
    shiftName: 'Morning Shift (06:00 - 15:00)',
    date: todayStr,
    checkIn: `${todayStr}T05:50:10.000Z`,
    checkOut: `${todayStr}T15:05:00.000Z`,
    status: 'PRESENT',
    lateMinutes: 0,
    earlyMinutes: 0,
    overtimeMinutes: 5,
    effectiveWorkHours: 8.0,
    verificationMethod: 'BULK_EXCEL',
    ipAddress: '10.30.5.12',
    notes: 'Imported via Bulk Excel Shift Pagi Batch-01',
    createdAt: `${todayStr}T05:50:10.000Z`,
  },
  {
    id: 'att-4',
    userId: 'u-7',
    employeeCode: 'EMP-0007',
    employeeName: 'Siti Aliyah Putri',
    departmentName: 'Product & Design',
    branchName: 'Bandung R&D Digital Center',
    shiftName: 'Flexible Core Hours (40h/week)',
    date: todayStr,
    checkIn: `${todayStr}T09:15:00.000Z`,
    checkOut: null,
    status: 'PRESENT',
    lateMinutes: 0,
    earlyMinutes: 0,
    overtimeMinutes: 0,
    effectiveWorkHours: 2.2,
    verificationMethod: 'WEB_KIOSK',
    ipAddress: '10.15.2.4',
    notes: 'Presensi Kios Bandung Hub',
    createdAt: `${todayStr}T09:15:00.000Z`,
  },
  {
    id: 'att-5',
    userId: 'u-8',
    employeeCode: 'EMP-0008',
    employeeName: 'Budi Santoso',
    departmentName: 'Finance & Accounting',
    branchName: 'Headquarter Sudirman',
    shiftName: 'Standard Office (08:00 - 17:00)',
    date: todayStr,
    checkIn: null,
    checkOut: null,
    status: 'ON_LEAVE',
    lateMinutes: 0,
    earlyMinutes: 0,
    overtimeMinutes: 0,
    effectiveWorkHours: 0,
    verificationMethod: 'WEB_KIOSK',
    notes: 'Cuti Tahunan (Disetujui HR)',
    createdAt: `${todayStr}T00:00:00.000Z`,
  },
  // Yesterday's records
  {
    id: 'att-6',
    userId: 'u-4',
    employeeCode: 'EMP-0004',
    employeeName: 'Dimas Anggara',
    departmentName: 'Software Engineering & IT',
    branchName: 'Headquarter Sudirman',
    shiftName: 'Standard Office (08:00 - 17:00)',
    date: yesterdayStr,
    checkIn: `${yesterdayStr}T07:50:00.000Z`,
    checkOut: `${yesterdayStr}T19:30:00.000Z`,
    status: 'OVERTIME',
    lateMinutes: 0,
    earlyMinutes: 0,
    overtimeMinutes: 150,
    effectiveWorkHours: 10.5,
    verificationMethod: 'WEB_KIOSK',
    ipAddress: '10.240.12.88',
    notes: 'Deploy production release v2.4',
    createdAt: `${yesterdayStr}T07:50:00.000Z`,
  },
  {
    id: 'att-7',
    userId: 'u-5',
    employeeCode: 'EMP-0005',
    employeeName: 'Nadia Saphira',
    departmentName: 'Software Engineering & IT',
    branchName: 'Headquarter Sudirman',
    shiftName: 'Standard Office (08:00 - 17:00)',
    date: yesterdayStr,
    checkIn: `${yesterdayStr}T08:02:00.000Z`,
    checkOut: `${yesterdayStr}T17:05:00.000Z`,
    status: 'PRESENT',
    lateMinutes: 0,
    earlyMinutes: 0,
    overtimeMinutes: 5,
    effectiveWorkHours: 8.0,
    verificationMethod: 'WEB_KIOSK',
    ipAddress: '10.240.12.89',
    notes: 'Regular attendance',
    createdAt: `${yesterdayStr}T08:02:00.000Z`,
  },
  {
    id: 'att-8',
    userId: 'u-6',
    employeeCode: 'EMP-0006',
    employeeName: 'Fajar Hidayat',
    departmentName: 'Operations & Logistics',
    branchName: 'Surabaya Tech & Operations',
    shiftName: 'Morning Shift (06:00 - 15:00)',
    date: yesterdayStr,
    checkIn: `${yesterdayStr}T06:45:00.000Z`,
    checkOut: `${yesterdayStr}T15:00:00.000Z`,
    status: 'LATE',
    lateMinutes: 45,
    earlyMinutes: 0,
    overtimeMinutes: 0,
    effectiveWorkHours: 7.25,
    verificationMethod: 'BULK_EXCEL',
    ipAddress: '10.30.5.12',
    notes: 'Terlambat pergantian shift armada',
    createdAt: `${yesterdayStr}T06:45:00.000Z`,
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-1',
    userId: 'u-8',
    employeeCode: 'EMP-0008',
    employeeName: 'Budi Santoso',
    departmentName: 'Finance & Accounting',
    leaveType: 'ANNUAL',
    startDate: todayStr,
    endDate: todayStr,
    totalDays: 1,
    reason: 'Urusan keluarga di luar kota',
    status: 'HR_APPROVED',
    approvedBy: 'Clarissa Maharani (HR)',
    reviewNotes: 'Disetujui sesuai jatah sisa cuti',
    createdAt: `${yesterdayStr}T09:00:00.000Z`,
  },
  {
    id: 'lr-2',
    userId: 'u-4',
    employeeCode: 'EMP-0004',
    employeeName: 'Dimas Anggara',
    departmentName: 'Software Engineering & IT',
    leaveType: 'SPECIAL',
    startDate: '2026-09-12',
    endDate: '2026-09-14',
    totalDays: 3,
    reason: 'Menghadiri Konferensi Cloud Engineering 2026',
    status: 'PENDING',
    approvedBy: null,
    reviewNotes: 'Menunggu review Manager Reza Pratama',
    createdAt: `${todayStr}T08:00:00.000Z`,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    actorId: 'u-2',
    actorName: 'Clarissa Maharani',
    actorRole: 'HR_ADMIN',
    action: 'BULK_EXCEL_IMPORT',
    entityType: 'AttendanceRecord',
    entityId: 'batch-20260903',
    details: 'Berhasil mengimpor 32 baris absensi cabang Surabaya dari file Excel',
    ipAddress: '10.240.10.15',
    createdAt: `${yesterdayStr}T16:30:00.000Z`,
  },
  {
    id: 'log-2',
    actorId: 'u-1',
    actorName: 'Alexander Bramantyo',
    actorRole: 'SUPER_ADMIN',
    action: 'SHIFT_POLICY_UPDATE',
    entityType: 'Shift',
    entityId: 's-4',
    details: 'Memperbarui toleransi grace period Shift Fleksibel menjadi 30 menit',
    ipAddress: '10.240.10.1',
    createdAt: `${yesterdayStr}T14:15:00.000Z`,
  },
  {
    id: 'log-3',
    actorId: 'u-2',
    actorName: 'Clarissa Maharani',
    actorRole: 'HR_ADMIN',
    action: 'LEAVE_APPROVE',
    entityType: 'LeaveRequest',
    entityId: 'lr-1',
    details: 'Menyetujui permohonan cuti tahunan Budi Santoso (1 hari)',
    ipAddress: '10.240.10.15',
    createdAt: `${yesterdayStr}T10:00:00.000Z`,
  },
];

export const INITIAL_IMPORT_BATCHES: BulkImportBatch[] = [
  {
    id: 'batch-01',
    fileName: 'Attendance_Log_Branch_Surabaya_W35.xlsx',
    fileSize: 45200,
    totalRows: 35,
    successCount: 32,
    errorCount: 3,
    warningCount: 4,
    uploadedByName: 'Clarissa Maharani',
    uploadedByRole: 'HR_ADMIN',
    createdAt: `${yesterdayStr}T16:28:10.000Z`,
    errorSummary: '3 baris NIK tidak ditemukan di database cabang',
  },
  {
    id: 'batch-02',
    fileName: 'Rekap_Presensi_Agustus_2026_AllBranch.xlsx',
    fileSize: 128400,
    totalRows: 120,
    successCount: 120,
    errorCount: 0,
    warningCount: 8,
    uploadedByName: 'Clarissa Maharani',
    uploadedByRole: 'HR_ADMIN',
    createdAt: '2026-09-01T11:00:00.000Z',
    errorSummary: null,
  },
];
